notifications:
    resource: "@notificationsBundle/Resources/config/routing.yml"
    prefix:   /notifications

profiles:
    resource: "@profilesBundle/Resources/config/routing.yml"
    prefix:   /profile

forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /forum



_index_login:
    resource: "@IndexIndexBundle/Resources/config/routing.yml"
    prefix:   /

    
_classes:
    resource: "@classesclassBundle/Resources/config/routing.yml"
    prefix:   /classes


_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler
    
_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"



fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profilez    
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profilezz