classesclass_update:
    path:  /update/
    defaults: { _controller: classesclassBundle:Default:update }

classesclass_add:
    path:  /add/
    defaults: { _controller: classesclassBundle:Default:add }
    
    
classesclass_delete:
    path:  /delete/
    defaults: { _controller: classesclassBundle:Default:delete }

classesclass_search_datatables:
    path:  /search/datatables
    defaults: { _controller: classesclassBundle:Default:searchDatatables }