profiles_viewprofile:
    path:     /view/{id}
    defaults: { _controller: profilesBundle:Default:viewProfile }

profiles_editprofile:
    path:     /edit/
    defaults: { _controller: profilesBundle:Default:editProfile }

profiles_editprofile_save:
    path:     /edit/save/
    defaults: { _controller: profilesBundle:Default:editProfileSave }

profiles_gettopics:
    path:     /gettopics/
    defaults: { _controller: profilesBundle:Default:getTopics }
profiles_getposts:
    path:     /getposts/
    defaults: { _controller: profilesBundle:Default:getPosts }

profiles_getmessages:
    path:     /getmessages/
    defaults: { _controller: profilesBundle:Default:getVisitorsMessages}

profiles_addvisitormessage:
    path:     /addVisitorMessage/
    defaults: { _controller: profilesBundle:Default:addVisitorMessage }


profiles_index:
    path:     /
    defaults: { _controller: profilesBundle:Default:index }    

profiles_send_friend_request:
    path:     /sendfriendrequest/
    defaults: { _controller: profilesBundle:Default:sendFriendRequest }  

profiles_remove_friend:
    path:     /removefriend/
    defaults: { _controller: profilesBundle:Default:removeFriend }  

profiles_addFriendButton:
    path:     /addFriendButton/
    defaults: { _controller: profilesBundle:Default:addFriendButton }  


profiles_make_friend_data:
    path:     /makedata/
    defaults: { _controller: profilesBundle:Default:fillInFriendData } 

profiles_messages:
    path:     /messages/
    defaults: { _controller: profilesBundle:Messages:index } 

profiles_messages_send_message:
    path:     /messages/sendmessage/
    defaults: { _controller: profilesBundle:Messages:sendMessage } 

profiles_messages_send_message_saved:
    path:     /messages/sendmessage/saved/
    defaults: { _controller: profilesBundle:Messages:sendMessagesSaved } 

profiles_messages_reset_seen:
    path:     /messages/resetseen
    defaults: { _controller: profilesBundle:Messages:resetSeen } 