forum_index:
    path:     /
    defaults: { _controller: ForumBundle:Default:index }

forum_inforum:
    path:     /{forumid}/{title}.html
    defaults: { _controller: ForumBundle:Default:inforum }    

forum_inforum_PostNewTopic:
    path:     /postnewtopics
    defaults: { _controller: ForumBundle:Default:inforumPostNewTopic }   
