  
_index:
    pattern:  /
    defaults: { _controller: IndexIndexBundle:Default:index }
    
_index_register:
    pattern:  /register/
    defaults: { _controller: IndexIndexBundle:Default:register }  


_index_generateAuthenticateSessionId:
    pattern:  /generatesessionid
    defaults: { _controller: IndexIndexBundle:Default:generateAuthenticateSessionId }

_index_private_messages_count:
    pattern:  /privateMessagesCount
    defaults: { _controller: IndexIndexBundle:Header:privateMessagesCount }

_index_subscribe:
    pattern:  /subscribe/
    defaults: { _controller: IndexIndexBundle:Header:subscribe }    