parameters:
    index.controller.default: Index\IndexBundle\Controller\DefaultController
services:
    twigextensions:
        class: Index\IndexBundle\Twig\Extension\VarsExtension
        arguments: [@service_container]
        tags: 
            - { name: 'twig.extension' }